### PR TITLE
Support multiple movies db scores

### PR DESCRIPTION
**Pull request by lightglitch**
It still needs some testing but feedback is welcome.

### CODE REVIEW

**Comment by desimaniac** [comment]
Thanks. Will check this out in a bit

**Comment by crypto-vault** [comment]
I hope this gets merged. Omdb lacks a lot on rotten ratings for new releases. Using IMDb would get some more results.

**Comment by crypto-vault** [comment]
You're using a float for imdb_rating, but when logging you're using an integer so you get something like: "Minimum Rotten Tomatoes score of 50%, IMDB score 5%, Metacritic score  50% requested." when using IMDB score 5.0 as an example. You need to replace logging from %d to  %.1f

**Comment by lightglitch** [comment]
@crypto-vault thx for the feedback

**Comment by lightglitch** [comment]
@desimaniac can you merge this, thx

**Comment by hyperhydra98** [comment]
@l3uddz @desimaniac @horjulf @nemchik @zenjabba Would one you you be able to please help merge this? It would be a great addition to Traktarr as many OMDb results lack RT ratings.

**Comment by jacobtipp** [comment]
> 
> 
> @l3uddz @desimaniac @horjulf @nemchik @zenjabba Would one you you be able to please help merge this? It would be a great addition to Traktarr as many OMDb results lack RT ratings.

I agree, I run traktarr on several docker containers and being able to use ratings from other providers would be a great addition

**Comment by lightglitch** [comment]
I stopped using traktarr and created my own tool https://github.com/lightglitch/seekerr

**Pull request closed without merging**
